name: CI
on:
  push:
    branches: [main]
jobs:
  UnitTest:
    runs-on: unbuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 7.14.0
      - name: Install
        run: pnpm install
      - name: Run Test
        run: pnpm run test:run
